### ISSUE TITLE
Enum syntactic sugar

### ISSUE THREAD

**Issue by jzabroski** [eoincampbell/combinatorics#17]
It would be nice to be able to write the following:
```c#
var variations = Variations<MyEnum>(4, GenerateOption.WithRepetution);
```
In particular, I can see this useful in generating AutoFixture fixtures for EF entities where the property is an Enum.  I usually want to write something to the effect of `One.Of<MyEnum>`, or `UniqueList.Of<MyEnum(size: 4)`, etc.

**Comment by eoincampbell** [comment]
@jzabroski will pick this up with you once I get the v2.0 on the other ticket sorted 👍

**Comment by eoincampbell** [comment]
Just having a think about this, I'm not sure how much value this would add...

It looks like you're looking for some sort of static method `Generate` on `Variations<T>` which would do the following for you.

```
public enum MyEnum
{
	One = 1,
	Two = 2,
	Three = 3
}
///...
var allPossibleEnums = Enum.GetValues(typeof(MyEnum)).Cast<MyEnum>(); <-- //this line here.

var variations = new Variations<MyEnum>(allPossibleEnums, 2, GenerateOption.WithoutRepetition);
```

I'm honestly not sure how much value this would bring. It's a 1 liner to do this yourself when you need variations of `enum`, yet to include it as an extension, you need to check that T and handle for non-enum situations as other messiness. I think I'd leave this one out to be honest.
